version: "3"

services:
  nginx:
    build: ./nginx
    links:
      - web:web
    ports:
      - "80:80"

  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data

  web:
    build: ./app
    links:
      - db
      - redis
    ports:
      - "8081"
    environment:
      PORT_NUMBER: 8081
      LOG_LEVEL: common
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: clusterdb
      PGPORT: 5432
