version: "3"

services:
  nginx:
    build: ./nginx
    links:
      - api_user:api_user
    ports:
      - "8080:8080"

  redis:
    image: redis

  api_user:
    build: ./app
    links:
      - redis
    ports:
      - "3001"
    environment:
      PORT_NUMBER: 3001
