version: "3"

services:
  nginx:
    build: ./nginx
    links:
      - web:web
    ports:
      - "80:80"

  web:
    build: ./app
    links:
      - redis
    ports:
      - "8081"
    environment:
      - PORT_NUMBER=8081
      - LOG_LEVEL=common

  redis:
    image: redis
