version: "3"

services:
  nginx:
    build: ./nginx
    links:
      - web1:web1
      - web2:web2
    ports:
      - "80:80"

  web1:
    build: ./app
    links:
      - redis
    ports:
      - "8081"
    environment:
      - PORT_NUMBER=8081
      - LOG_LEVEL=common
  web2:
    build: ./app
    links:
      - redis
    ports:
      - "8082"
    environment:
      - PORT_NUMBER=8082
      - LOG_LEVEL=common

  redis:
    image: redis
