version: "3"

services:
  nginx:
    build: ./nginx
    links:
      - web:web
    ports:
      - "80:80"

  redis:
    image: redis

  web:
    build: ./app
    links:
      - redis
    ports:
      - "8081"
    environment:
      PORT_NUMBER: 8081
